apiVersion: v1
kind: ServiceAccount
metadata:
  name: codelab
  annotations:
    # Replace me with your Google service account
    iam.gke.io/gcp-service-account: codelab@leebernick-test.iam.gserviceaccount.com