apiVersion: v1
kind: ServiceAccount
metadata:
  name: codelab
  annotations:
    # Replace me with your Google service account
    iam.gke.io/gcp-service-account: codelab@leebernick-test.iam.gserviceaccount.com
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: notify-google-chat
spec:
  params:
  - name: webhook-url
  - name: message
  steps:
  - name: notify
    image: gcr.io/leebernick-test/python-httplib # Docker image with python deps installed
    script: |
      #!/usr/bin/env python3
      from json import dumps
      from httplib2 import Http

      def main():
          """Hangouts Chat incoming webhook quickstart."""
          url = '$(params.webhook-url)'
          bot_message = {
              'text' : "$(params.message)"}

          message_headers = {'Content-Type': 'application/json; charset=UTF-8'}

          http_obj = Http()

          response = http_obj.request(
              uri=url,
              method='POST',
              headers=message_headers,
              body=dumps(bot_message),
          )

          print(response)

      if __name__ == '__main__':
          main()
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  workspaces:
  - name: source-code
  params:
  - name: image
  - name: chat-webhook-url
  tasks:
  - name: clone
    taskRef:
      name: git-clone
      bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.6
    workspaces:
    - name: output
      workspace: source-code
    params:
    - name: url
      value: https://github.com/lbernick/web-app-demo
  - name: build
    taskRef:
      name: docker-build
      bundle: gcr.io/tekton-releases/catalog/upstream/docker-build:0.1
    workspaces:
    - name: source
      workspace: source-code
    params:
    - name: image
      value: $(params.image)
    runAfter:
    - clone
  finally:
  - name: notify
    taskRef:
      name: notify-google-chat
    params:
    - name: webhook-url
      value: $(params.chat-webhook-url)
    - name: message
      value: "Build status: $(tasks.build.status)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-pipeline-run
spec:
  pipelineRef:
    name: ci-pipeline
  params:
  - name: image
    value: gcr.io/leebernick-test/web-app-demo
  - name: chat-webhook-url
    value: https://chat.googleapis.com/v1/spaces/AAAAGDLkJiM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=PJjU6o5bxDsarG_hgl6U6ZqOb8EM_L8DX3Lp5FhIVTQ%3D
  workspaces:
  - name: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  serviceAccountNames:
  - taskName: notify
    serviceAccountName: codelab