apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone
spec:
  params:
  - name: repo
  - name: user
  steps:
  - name: clone
    image: alpine/git
    script: |
      git clone https://github.com/$(params.user)/$(params.repo)
      ls $(params.repo)
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: clone-run
spec:
  taskRef:
    name: clone
  params:
  - name: repo
    value: web-app-demo
  - name: user
    value: lbernick
