apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: remote-ci-pipeline-run
spec:
  pipelineRef:
    resolver: git
    resource:
    - name: url
      value: https://github.com/lbernick/tekton-codelab.git
    - name: path
      value: basic-ci-pipeline/pipeline.yaml
    - name: branch
      value: main
  params:
  - name: image
    value: us-east1-docker.pkg.dev/leebernick-test/codelab/web-app-demo
  - name: registry
    value: us-east1-docker.pkg.dev
  workspaces:
  - name: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  serviceAccountNames:
  - taskName: build
    serviceAccountName: codelab # defined in serviceaccount.yaml