apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline-with-notify
spec:
  workspaces:
  - name: source-code
  params:
  - name: image
  - name: registry
  - name: chat-webhook-url
  tasks:
  - name: clone
    taskRef:
      name: git-clone
      bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.6
    workspaces:
    - name: output
      workspace: source-code
    params:
    - name: url
      value: https://github.com/lbernick/web-app-demo
  - name: build
    taskRef:
      name: docker-build
    workspaces:
    - name: source
      workspace: source-code
    params:
    - name: image
      value: $(params.image)
    - name: registry
      value: $(params.registry)
    runAfter:
    - clone
  finally:
  - name: notify
    taskRef:
      name: notify-google-chat
    params:
    - name: webhook-url
      value: $(params.chat-webhook-url)
    - name: message
      value: "Build status: $(tasks.build.status)"